import type { Metadata } from 'next'
import '../styles/fonts.scss'
import '../styles/globals.scss'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="ru">
			<body>{children}</body>
		</html>
	)
}
